image: archlinux
packages:
  - hugo
  - rsync
  - npm
  - go
secrets:
  - 5874ac5a-905e-4596-a117-fed1401c60ce
sources:
  - https://github.com/emersion/emersion.fr
tasks:
  - setup: |
      cd emersion.fr/themes/shimong/static
      npm install
  - openring: |
      cd emersion.fr
      ./openring-update.sh
  - build: |
      cd emersion.fr
      hugo
  - upload: |
      cd emersion.fr/public
      sshopts="-o StrictHostKeyChecking=no"
      rsync --rsh="ssh $sshopts" -rP \
          --delete \
          --delete-excluded \
          . deploy@emersion.fr:/srv/http/emersion.fr
triggers:
  - action: email
    condition: failure
    to: "<contact@emersion.fr>"
