baseURL = "https://emersion.fr/"
languageCode = "en-us"
title = "emersion"
copyright = "Creative Commons BY 3.0"
theme = "shimong"
pygmentsCodeFences = true
paginate = 100

[permalinks]
	blog = "/blog/:year/:slug/"

[taxonomies]
	tag = "tags"

[outputs]
	home = ["HTML"]
	section = ["HTML", "RSS", "Atom"]

[mediaTypes."application/atom+xml"]
	suffixes = ["xml"]

[outputFormats.RSS]
	mediaType = "application/xml"
	baseName = "rss"
[outputFormats.Atom]
	mediaType = "application/atom+xml"
	baseName = "atom"

[markup.goldmark.renderer]
	unsafe = true
